print("ESCOLHA DE AR CONDICIONADO")
print("Qual o tamanho da sala ou escritório?")
Comprimento =float(input("Comprimento da sala"))
Largura =float(input("Largura da sala"))
Altura =float(input("Altura da sala"))
Volume =Comprimento*Largura*Altura
print("Quantas portas e janelas tem no ambiente?")
Njanelas =int(input("Número de janelas da sala"))
NPortas =int(input("Número de Portas da sala"))
x = int(input("Quantas pessoas trabalham no ambiente?"))
x = int(input("Os aparelhos elétricos trabalham em regime contínuo; qual a capacidade (potência) de cada um?"))